apiVersion: apps/v1
kind: Deployment
metadata:
  name: apitest
spec:
  selector:
    matchLabels:
      app: apitest
  template:
    metadata:
      labels:
        app: apitest
    spec:
      containers:
      - name: apitest
        image: docker.io/guydw/kubeapitest:latest
        ports:
        - containerPort: 80
