apiVersion: apps/v1
kind: Deployment
metadata:
  name: apitest
  namespace: default
spec:
  selector:
    matchLabels:
      app: apitest
  template:
    metadata:
      labels:
        app: apitest
    spec:
      containers:
      - name: apitest
        image: docker.io/guydw/kubeapitest:v16
        ports:
        - containerPort: 80
