---
- hosts: localhost
  tasks:
    - name: create frontend namespace
      k8s:
        state: present
        src: ./namespaces/frontend-namespaces.yaml

    - name: create frontend deployment
      k8s:
        state: present
        src: ./frontend/frontend-deployment.yaml

    - name: create frontend service
      k8s:
        state: present
        src: ./frontend/frontend-service.yml

    - name: configure endpoint
      k8s:
        state: present
        src: ./endpoints/backend-service-endpoint.yaml
      