---
- hosts: localhost
  tasks:
    - pip:
        name: openshift

    - name: create the backend namespace
      k8s:
        state: present
        src: ./namespaces/backend-namespaces.yaml
      
    - name: Launch the backend deployment
      k8s:
        state: present
        src: ./backend-service/backend-deployment.yaml
    
    - name: create backend service
      k8s:
        state: present
        src: ./backend-service/backend-service.yaml

